### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir

### ISSUE THREAD

**Issue by starlod** [starlod/develop#4]
```
# gulp
Message:
    ENOENT: no such file or directory, scandir '/var/www/html/project/node_modules/node-sass/vendor'
Details:
    errno: -2
    code: ENOENT
    syscall: scandir
    path: /var/www/html/project/node_modules/node-sass/vendor
Stack:
Error: ENOENT: no such file or directory, scandir '/var/www/html/project/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (/var/www/html/project/node_modules/node-sass/lib/extensions.js:120:13)
    at foundBinariesList (/var/www/html/project/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/var/www/html/project/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/var/www/html/project/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/var/www/html/project/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/var/www/html/project/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by starlod** [comment]
```
# npm rebuild node-sass
```

`vendor`ディレクトリが生成されるので`gulp`がうまく通る。
